bcgov/nr-epd-organics-info

.github/workflows/merge.yml

---
- [Frontend](https://nr-omrr-transparency-2-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-2-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: merge workflow

---

charts/nr-omrr-transparency/values.yaml

---
- [Frontend](https://nr-omrr-transparency-3-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-3-frontend.apps.silver.devops.gov.bc.ca/api/)

feat: make pvc block than file

---

.github/workflows/.deploy.yml
charts/nr-omrr-transparency/Chart.yaml
charts/nr-omrr-transparency/templates/backend/templates/_helpers.tpl
charts/nr-omrr-transparency/templates/backend/templates/deployment.yaml
charts/nr-omrr-transparency/templates/backend/templates/hpa.yaml
charts/nr-omrr-transparency/templates/backend/templates/pdb.yaml
charts/nr-omrr-transparency/templates/backend/templates/service.yaml
charts/nr-omrr-transparency/templates/frontend/templates/_helpers.tpl
charts/nr-omrr-transparency/templates/frontend/templates/deployment.yaml
charts/nr-omrr-transparency/templates/frontend/templates/hpa.yaml
charts/nr-omrr-transparency/templates/frontend/templates/pdb.yaml
charts/nr-omrr-transparency/templates/frontend/templates/route.yaml
charts/nr-omrr-transparency/templates/frontend/templates/service.yaml
charts/nr-omrr-transparency/templates/secret.yaml
charts/nr-omrr-transparency/values.yaml
frontend/src/routes/index.tsx
frontend/vite.config.ts

---
- [Frontend](https://nr-omrr-transparency-19-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-19-frontend.apps.silver.devops.gov.bc.ca/api/)

refactor(helm)!: simplify HELM

---

.github/workflows/merge.yml

---
- [Frontend](https://nr-omrr-transparency-20-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-20-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(gha): prod params

---

frontend/src/components/Header.tsx

---
- [Frontend](https://nr-omrr-transparency-22-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-22-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: header color

---

.github/workflows/merge.yml

---
- [Frontend](https://nr-omrr-transparency-25-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-25-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(CD): merge fail

---

.github/workflows/merge.yml
charts/nr-omrr-transparency/templates/frontend/templates/pdb.yaml

---
- [Frontend](https://nr-omrr-transparency-27-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-27-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(HELM): PDB template

---

charts/nr-omrr-transparency/values.yaml
frontend/src/service/api-service.ts

---
- [Frontend](https://nr-omrr-transparency-30-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-30-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: image registry

---

backend/src/v1/object-store/object.store.service.ts

---
- [Frontend](https://nr-omrr-transparency-36-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-36-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(backend): skip empty lines while csv parsing.

---

backend/src/v1/types/omrr-data.ts
frontend/src/components/Dashboard.tsx
frontend/src/features/omrr/omrr-slice.ts
frontend/src/interfaces/omrr.ts

---
- [Frontend](https://nr-omrr-transparency-49-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-49-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: fix some dataset and add the new field, fix the hyperlink.

---

frontend/src/components/AuthorizationList.tsx

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
---
- [Frontend](https://nr-omrr-transparency-56-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-56-frontend.apps.silver.devops.gov.bc.ca/api/)
- …

chore: UI field rename

---

frontend/src/App.tsx
frontend/src/components/AuthorizationDetails.tsx
frontend/src/components/AuthorizationList.tsx
frontend/src/components/Dashboard.tsx
frontend/src/components/Header.tsx

---
- [Frontend](https://nr-omrr-transparency-57-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-57-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: header pin changes

---

frontend/.eslintrc
frontend/index.html
frontend/public/manifest.json
frontend/src/App.tsx
frontend/src/components/AuthorizationDetails.tsx
frontend/src/components/AuthorizationList.tsx
frontend/src/components/HeaderWithRouting.tsx
frontend/src/features/omrr/omrr-slice.ts
frontend/src/index.css

---
- [Frontend](https://nr-omrr-transparency-60-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-60-frontend.apps.silver.devops.gov.bc.ca/api/)

feat(frontend): Auth details page

---

frontend/Caddyfile
frontend/src/routes/index.tsx

---
- [Frontend](https://nr-omrr-transparency-62-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-62-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: wildcard route

---

frontend/src/components/AuthorizationDetails.tsx

---
- [Frontend](https://nr-omrr-transparency-65-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-65-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: formatting and scroll

---

frontend/src/components/AuthorizationList.tsx
frontend/src/components/HeaderWithRouting.tsx

---
- [Frontend](https://nr-omrr-transparency-66-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-66-frontend.apps.silver.devops.gov.bc.ca/api/)

feat(frontend): header changes

---

frontend/src/components/AuthorizationDetails.tsx

---
- [Frontend](https://nr-omrr-transparency-67-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-67-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: Add wrap for text overflow.

---

backend/src/app.module.ts
backend/src/metrics.controller.ts

---
- [Frontend](https://nr-omrr-transparency-68-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-68-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: remove prisma related stuff from code as there is no DB at this moment

---

frontend/src/components/AuthorizationList.tsx
frontend/src/features/omrr/omrr-slice.ts

---
- [Frontend](https://nr-omrr-transparency-72-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-72-frontend.apps.silver.devops.gov.bc.ca/api/)

feat(frontend): making active records by default

---

frontend/package.json

Linting for frontend.  Useful for two current linting-related PRs.
---
- [Frontend](https://nr-omrr-transparency-128-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-128-frontend.apps.silver.devops.gov.bc.ca/api/)

feat(ci): setup linters

---

backend/src/v1/object-store/object.store.service.ts
backend/src/v1/tasks/task.service.ts

---
- [Frontend](https://nr-omrr-transparency-141-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-141-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(backend): data not getting updated with latest csv upload.

---

.github/codeowners

---
- [Frontend](https://nr-omrr-transparency-148-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-148-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: adding Aman to codeowners

---

README.md

Just updates the readme.
---
- [Frontend](https://nr-omrr-transparency-144-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-omrr-transparency-144-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: add more details to readme

---

.github/workflows/pr-open.yml
.github/workflows/soak-test.yml
tests/load/backend-test.js
tests/load/frontend-test.js

---
- [Frontend](https://nr-epd-organics-info-155-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-155-frontend.apps.silver.devops.gov.bc.ca/api/)

feat(load-test): Soak Tests which runs against test environment for 10 mins, every hour on a schedule.

---

.github/workflows/pr-open.yml
.github/workflows/soak-test.yml

---
- [Frontend](https://nr-epd-organics-info-156-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-156-frontend.apps.silver.devops.gov.bc.ca/api/)

fix:  soak test URL and add results to pr open

---

.github/workflows/.deploy.yml
backend/package.json
frontend/public/manifest.json

---
- [Frontend](https://nr-epd-organics-info-166-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-166-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(CI): E2E trigger during PR

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

---
- [Frontend](https://nr-epd-organics-info-181-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-181-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(CI): bug introduced in PR179

---

backend/package-lock.json
frontend/package-lock.json
frontend/package.json

---
- [Frontend](https://nr-epd-organics-info-187-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-187-frontend.apps.silver.devops.gov.bc.ca/api/)

fix(deps): audit fix and remove deprecated dev deps

---

frontend/src/components/HorizontalScroller.test.tsx
frontend/src/components/HorizontalScroller.tsx
frontend/src/hooks/useMyLocation.tsx
frontend/src/hooks/useSwipe.test.tsx
frontend/src/hooks/useSwipe.tsx
frontend/src/index.css
frontend/src/pages/map/drawer/MapBottomDrawer.tsx
frontend/src/pages/map/layers/MyLocationMarker.tsx
frontend/src/pages/map/search/MapSearch.tsx

Add basic swipe gestures to the bottom drawer component (up/down) and horizontal scrolling buttons (left/right).
Fixes #192 
---
- [Frontend](https://nr-epd-organics-info-200-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-200-frontend.apps.silver.devops.gov.bc.ca/api/)

feat: Add swipe gestures

---

frontend/e2e/pages/auth.list.ts
frontend/src/components/LocationIconButton.test.tsx
frontend/src/components/LocationIconButton.tsx
frontend/src/components/SearchInput.css
frontend/src/features/omrr/omrr-slice.ts
frontend/src/features/omrr/omrr-utils.ts
frontend/src/hooks/useMyLocation.tsx
frontend/src/pages/authorizationList/ExportResultsButton.test.tsx
frontend/src/pages/authorizationList/ExportResultsButton.tsx
frontend/src/pages/guidance/GuidancePage.test.tsx
frontend/src/test-setup.ts
frontend/src/utils/utils.test.ts
frontend/src/utils/utils.ts

Changed the GPS Location icon to work as a toggle. When it is clicked on, the search results will be sorted by proximity to the user's location, and the icon will be a blue color.
When clicked off, the results will revert to original sorted order.
Also changed the export csv filename to the format Konane requested.
Fixes #194 #195 
---
- [Frontend](https://nr-epd-organics-info-205-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-205-frontend.apps.silver.devops.gov.bc.ca/api/)
- [Merge …

feat: Authorizations list GPS location toggle

---

frontend/src/pages/authorizationList/ExportResultsButton.test.tsx
frontend/src/pages/authorizationList/ExportResultsButton.tsx

Change filename from `OMMR_...` to `OMRR_...`
Fixes #195 
---
- [Frontend](https://nr-epd-organics-info-209-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-209-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: CSV filename typo

---

backend/package-lock.json

---
- [Frontend](https://nr-epd-organics-info-217-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-217-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: security updates

---

.github/workflows/merge.yml

---
- [Frontend](https://nr-epd-organics-info-219-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-219-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: enable docs for test and prod

---

.github/workflows/.deploy.yml
.github/workflows/pr-close.yml
.github/workflows/scheduled.yml

---
- [Frontend](https://nr-epd-organics-info-229-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-229-frontend.apps.silver.devops.gov.bc.ca/api/)

chore(ci): handle gh runner oc removal

---

charts/nr-epd-organics-info/templates/frontend/templates/deployment.yaml

---
- [Frontend](https://nr-epd-organics-info-320-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-320-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: caddy warning

---

.github/workflows/analysis.yml

---
- [Frontend](https://nr-epd-organics-info-329-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-329-frontend.apps.silver.devops.gov.bc.ca/api/)

ci: catch canceled jobs

---

.github/workflows/analysis.yml

---
- [Frontend](https://nr-epd-organics-info-331-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-331-frontend.apps.silver.devops.gov.bc.ca/api/)

ci(fix): catch canceled jobs

---

charts/nr-epd-organics-info/values.yaml

---
- [Frontend](https://nr-epd-organics-info-335-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-335-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: remove limits as it is removed from OpenShift platform

---

backend/Dockerfile
charts/nr-epd-organics-info/templates/frontend/templates/deployment.yaml
charts/nr-epd-organics-info/values.yaml

---
- [Frontend](https://nr-epd-organics-info-336-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-336-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: resource allocation

---

frontend/src/constants/data-layers.ts

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
---
- [Frontend](https://nr-epd-organics-info-341-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-341-frontend.apps.silver.devops.gov.bc.ca/api/)
- …

fix(deps): Remove ALR notice of intent layer

---

charts/nr-epd-organics-info/templates/frontend/templates/route.yaml

---
- [Frontend](https://nr-epd-organics-info-344-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-344-frontend.apps.silver.devops.gov.bc.ca/api/)

chore: add rate limiting

---

.github/workflows/analysis.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

---
- [Frontend](https://nr-epd-organics-info-353-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-353-frontend.apps.silver.devops.gov.bc.ca/api/)

chore(ci): actions moved to bcgov org

---

.github/workflows/scheduled.yml

---
- [Frontend](https://nr-epd-organics-info-354-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-354-frontend.apps.silver.devops.gov.bc.ca/api/)

chore(ci): use GH runner ubuntu-24.04

---

frontend/src/pages/authorizationDetails/DetailsGridItems.tsx
frontend/src/pages/authorizationDetails/DetailsSection.test.tsx

- Update the layout and styling to match the Figma mockup
---
- [Frontend](https://nr-epd-organics-info-359-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-359-frontend.apps.silver.devops.gov.bc.ca/api/)

refactor: Updating the Organic Matter Used for Composting

---

frontend/src/pages/authorizationDetails/AuthorizationDetails.tsx
frontend/src/pages/authorizationDetails/ContactSection.tsx

- New Contact Us Component
- Currently displayed at the bottom of the Authorization Details
- The Auth Number is passed in and displayed in the instructions
---
- [Frontend](https://nr-epd-organics-info-360-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-360-frontend.apps.silver.devops.gov.bc.ca/api/)

feat: New Contact Us Component

---

frontend/src/pages/authorizationDetails/DetailsMap.tsx
frontend/src/pages/authorizationDetails/LocationSection.tsx

- Updated Pin
- Map scales to 50% width on wide screens.
---
- [Frontend](https://nr-epd-organics-info-370-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-370-frontend.apps.silver.devops.gov.bc.ca/api/)

refactor: Minor formatting fixes for details map

---

charts/nr-epd-organics-info/templates/backend/templates/deployment.yaml
charts/nr-epd-organics-info/templates/frontend/templates/deployment.yaml

Currently multiple commits in a single PR , does not rollout properly
---
- [Frontend](https://nr-epd-organics-info-382-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-382-frontend.apps.silver.devops.gov.bc.ca/api/)

fix: rollout

---

frontend/src/pages/contactUs/ContactUs.tsx

- On some mobile platforms the URLs don't wrap... Force it here.
---
- [Frontend](https://nr-epd-organics-info-386-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-epd-organics-info-386-frontend.apps.silver.devops.gov.bc.ca/api/)

feat: Force wrapping long urls
